[package]
name = "my_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.1"
dotenv = "0.15.0"
actix-web = "4"
mysql = "22.1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }