version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: "always"
    environment:
      POSTGRES_USER: actix
      POSTGRES_PASSWORD: actix
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
#  dev:
#    image: "rust:latest"
#    volumes:
#      - .:/blog_server
#    environment:
#      SERVER_PORT: "8080"