version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: "always"
    env_file:
      - ./.env
    ports:
      - "7878:5432"
#  dev:
#    image: "rust:latest"
#    volumes:
#      - .:/blog_server
#    environment:
#      SERVER_PORT: "8080"